"""
##### Task 1
Create a "Madlib" that has the users enter in a variety of noun/verb/adjectives.
When they press a button, it should update the contents of a label to display
the completed madlib.
What is a madlib? Visit https://www.madlibs.com/printables/ to see some Madlibs
you might use in your assignment
"""

import tkinter as tk 
from tkinter import *

win = tk.Tk()
win.title("madlib")

noutput = StringVar()
noutput.set("name")
thoutput = StringVar()
thoutput.set("theme")
poutput = StringVar()
poutput.set("a place")
doutput = StringVar()
doutput.set("day of the week")
toutput = StringVar()
toutput.set("time")
voutput = StringVar()
voutput.set("verb")
aoutput = StringVar()
aoutput.set("animal")
bpoutput = StringVar()
bpoutput.set("body part")
cioutput = StringVar()
cioutput.set("contact information")

def clickFunction():
    name = e1.get()
    theme = e2.get()
    place = e3.get()
    day = e4.get()
    time = e5.get()
    verb = e6.get()
    animal = e7.get()
    bodyp = e8.get()
    contacti = e9.get()

    n_entry.delete(0,END)
    n_entry.insert(0,name)
    th_entry.delete(0,END)
    th_entry.insert(0,theme)
    p_entry.delete(0,END)
    p_entry.insert(0,place)
    d_entry.delete(0,END)
    d_entry.insert(0,day)
    t_entry.delete(0,END)
    t_entry.insert(0,time)
    v_entry.delete(0,END)
    v_entry.insert(0,verb)
    a_entry.delete(0,END)
    a_entry.insert(0,animal)
    bp_entry.delete(0,END)
    bp_entry.insert(0,bodyp)
    ci_entry.delete(0,END)
    ci_entry.insert(0,contacti)

l1 = Label(win,text="name:")
e1 = Entry(win, width=15)
l2 = Label(win,text="theme:")
e2 = Entry(win, width=15)
l3 = Label(win,text="a place:")
e3 = Entry(win, width=15)
l4 = Label(win,text="day of the week:")
e4 = Entry(win, width=15)
l5 = Label(win,text="time:")
e5 = Entry(win, width=15)
l6 = Label(win,text="verb:")
e6 = Entry(win, width=15)
l7 = Label(win,text="animal")
e7 = Entry(win, width=15)
l8 = Label(win,text="body part:")
e8 = Entry(win, width=15)
l9 = Label(win,text="contact information:")
e9 = Entry(win, width=15)

b1 = Button(win,text="Update madlib", command=clickFunction)

l10 = Label(win,text="is having a")
l11 = Label(win,text="party!")
l12 = Label(win,text="It's going to be at the")
l13 = Label(win,text="on")
l14 = Label(win,text="Please make sure to show up at")
l15 = Label(win,text=", or else")
l16 = Label(win,text="you will be required to")
l17 = Label(win,text=" on a/an")
l18 = Label(win,text="with your")
l19 = Label(win,text="RSVP at")
l20 = Label(win,text=" ")

n_entry = Entry(win, width=15, textvariable=noutput)
th_entry = Entry(win, width=15, textvariable=thoutput)
p_entry = Entry(win, width=15, textvariable=poutput)
d_entry = Entry(win, width=15, textvariable=doutput)
t_entry = Entry(win, width=15, textvariable=toutput)
v_entry = Entry(win, width=15, textvariable=voutput)
a_entry = Entry(win, width=15, textvariable=aoutput)
bp_entry = Entry(win, width=15, textvariable=bpoutput)
ci_entry = Entry(win, width=20, textvariable=cioutput)

l1.grid(row=1,column=1)
e1.grid(row=1,column=2)
l2.grid(row=1,column=3)
e2.grid(row=1,column=4)
l3.grid(row=2,column=1)
e3.grid(row=2,column=2)
l4.grid(row=2,column=3)
e4.grid(row=2,column=4)
l5.grid(row=3,column=1)
e5.grid(row=3,column=2)
l6.grid(row=3,column=3)
e6.grid(row=3,column=4)
l7.grid(row=4,column=1)
e7.grid(row=4,column=2)
l8.grid(row=4,column=3)
e8.grid(row=4,column=4)
l9.grid(row=5,column=1)
e9.grid(row=5,column=2)

b1.grid(row=5,column=4)

l20.grid(row=6,column=1)

n_entry.grid(row=7,column=1)
l10.grid(row=7,column=2)
th_entry.grid(row=7,column=3)
l11.grid(row=7,column=4)
l12.grid(row=8,column=1,columnspan=2)
p_entry.grid(row=8,column=2,columnspan=2)
l13.grid(row=9,column=1,columnspan=2)
d_entry.grid(row=9,column=2)
l14.grid(row=9,column=3)
t_entry.grid(row=10,column=1)
l15.grid(row=10,column=2)
l16.grid(row=10,column=3)
v_entry.grid(row=11,column=1)
l17.grid(row=11,column=2)
a_entry.grid(row=11,column=3)
l18.grid(row=12,column=1)
bp_entry.grid(row=12,column=2)
l19.grid(row=13,column=2,columnspan=2)
ci_entry.grid(row=13,column=3,columnspan=2)

win.mainloop()